
import './WritingPart.scss';

const WritingPart = () => {
  return (
    <article className="left">
      <p className="leftWritingPara">
        Enter input to get <span className="blueColor">Writing Assistant</span>
      </p>
      <div className="leftWritingMenu">
        <div className="leftFieldBox">
          <label htmlFor="word-count">Words count: </label>
          <input className="leftInputCountField numberField" type="number" />
        </div>
        <div className="leftFieldBox">
          <label htmlFor="prompt">Prompt: </label>
          <select className="leftInputCountField" name="prompt" id="">
            <option value="Select">Select</option>
          </select>
        </div>

        <div className="leftFieldBox">
          <label htmlFor="prompt">Creativity: </label>
          <select className="leftInputCountField" name="prompt" id="">
            <option value="Select">Select</option>
          </select>
        </div>
      </div>

      <p className="leftWordsCharacterCount">
        <span>Word: 00 </span> | <span> character: 0/250</span>
      </p>

      <div className="leftWritingContent">
        <ul className="top">
          <li className="keywordShadow">B</li>
          <li className="keywordShadow">I</li>
          <li>hyperlink</li>
          <li>text cut</li>
          <li>underline</li>
          <li>underline</li>
        </ul>
        <p className="leftParagraph">
          As artificial intelligence continues to evolve, it is becoming
          increasingly capable of generating original and insightful content.
          This blog post is a prime example; the title was generated by AI
          within 10 seconds. AI is quickly becoming a powerful tool for content
          creators and marketers alike.
        </p>
      </div>

    </article>
  );
};

export default WritingPart;
