
import './ParaGroup.scss';

const ParaGroup = () => {
  return (
    <article className="right">
      <button className="button rightBtnCenter  w-100">Write for me</button>
      <div className="copyParaGroup">
        <p className="rightClearText">Clear</p>
        <div className="rightParaGroup">
          <span>Copy</span>
          <p className="rightParagraph">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds.
          </p>
        </div>
        <div className="rightParaGroup">
          <span>Copy</span>
          <p className="rightParagraph">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds.
          </p>
        </div>
        <div className="rightParaGroup">
          <span>Copy</span>
          <p className="rightParagraph">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds.
          </p>
        </div>
        <div className="rightParaGroup">
          <span>Copy</span>
          <p className="rightParagraph">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds.
          </p>
        </div>
      </div>
    </article>
  );
};

export default ParaGroup;
